const DeleteIngredientsPreferencesIngredientId = {"metadata":{"allOf":[{"type":"object","properties":{"ingredient_id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Ingredient ID"}},"required":["ingredient_id"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"401":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetIngredients = {"metadata":{"allOf":[{"type":"object","properties":{"begins_with":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Filter ingredients that begin with these characters"},"ends_with":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Filter ingredients that end with these characters"},"limit":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"Limit the number of ingredients returned"}},"required":[]}]},"response":{"200":{"items":{"properties":{"ingredients":{"items":{"properties":{"approved":{"description":"Users can insert custom ingredients, but must be approved first by admins","type":"boolean"},"carbs":{"type":"number"},"fat":{"type":"number"},"id":{"type":"string"},"is_main_ingredient":{"description":"Main ingredients are used in the calculation of the macros of a recipe","type":"boolean"},"name":{"type":"string"},"protein":{"type":"number"},"quantity_measurement":{"type":"string"}},"type":"object"},"type":"array"}},"type":"object"},"type":"array","$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetIngredientsIngredientId = {"metadata":{"allOf":[{"type":"object","properties":{"ingredient_id":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Ingredient ID"}},"required":["ingredient_id"]}]},"response":{"200":{"properties":{"ingredient":{"properties":{"approved":{"description":"Users can insert custom ingredients, but must be approved first by admins","type":"boolean"},"carbs":{"type":"number"},"fat":{"type":"number"},"id":{"type":"string"},"is_main_ingredient":{"description":"Main ingredients are used in the calculation of the macros of a recipe","type":"boolean"},"name":{"type":"string"},"protein":{"type":"number"},"quantity_measurement":{"type":"string"}},"type":"object"}},"type":"object","$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetIngredientsPreferences = {"response":{"200":{"items":{"properties":{"ingredients":{"items":{"type":"string"},"type":"array"},"user_id":{"type":"string"}},"type":"object"},"type":"array","$schema":"http://json-schema.org/draft-04/schema#"},"401":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostIngredientsPreferences = {"body":{"properties":{"ingredient_ids":{"items":{"type":"string"},"type":"array"},"user_id":{"type":"string"}},"type":"object","$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"properties":{"ingredient_ids":{"items":{"type":"string"},"type":"array"}},"type":"object","$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"401":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"404":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
export { DeleteIngredientsPreferencesIngredientId, GetIngredients, GetIngredientsIngredientId, GetIngredientsPreferences, PostIngredientsPreferences }
