FROM node:20

WORKDIR /usr/src/frontend

COPY package.json ./

RUN npm install -g pnpm

RUN pnpm install

COPY . .

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

# for deploying the build version

# RUN bun next build
# and
# RUN bun next start

# OR for sart Next.js in development, comment above two lines and uncomment below line

ENTRYPOINT ["pnpm", "run", "dev", "-p", "3000"]