FROM golang:latest as builder

WORKDIR /usr/src/backend

# Auto-reloading!
RUN go install github.com/cosmtrek/air@latest

# Copy the script into the image
COPY wait-for-it.sh /usr/src/backend/wait-for-it.sh
# Make the script executable
RUN chmod +x /usr/src/backend/wait-for-it.sh

ENV IS_DEV="true"

COPY . .
RUN go mod tidy