FROM oven/bun:latest

WORKDIR /usr/src/seed

# Install dependencies
COPY package.json .
RUN bun install

# Copy the script into the image
COPY wait-for-it.sh /usr/src/backend/wait-for-it.sh
# Make the script executable
RUN chmod +x /usr/src/backend/wait-for-it.sh

RUN apt update && apt install -y make


# Copy source code
COPY . .
